spring:
  datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mobilele?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
      password: ${MYSQL_PASSWORD:12345}
      username: ${MYSQL_USER:root}
  jpa:
   database-platform: org.hibernate.dialect.MySQL8Dialect
   defer-datasource-initialization: true
   hibernate:
    ddl-auto: update
    open-in-view: false
    properties:
    hibernate:
        format_sql: true

  sql:
    init:
      mode: never
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    resources: # Static resources
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
  security:
    user:
      name: user
#      password: password

logging:
    level:
      org:
        hibernate:
          type:
            descriptor: TRACE
          SQL: DEBUG
        nodeValue: WARN
      blog: WARN
server:
    port: 8080


#proper
#      spring:
#        datasource:
#          driverClassName: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mobilele?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
#          username: ${MYSQL_USER:root}
#          password: ${MYSQL_PASSWORD:}
#        jpa:
#          database-platform: org.hibernate.dialect.MySQLDialect
#          defer-datasource-initialization: true
#          hibernate:
#            ddl-auto: update
#        sql:
#          init:
#            mode: always
#        mvc:
#          hiddenmethod:
#            filter:
#              enabled: true
#
#      default.admin.pass: ${DEFAULT_ADMIN_PASS:topsecret}
#      logging:
#        level:
#          org.springframework: DEBUG